#!/usr/bin/env ruby

$LOAD_PATH << './lib'

require 'multi_json'
require 'json-schema'
require 'aws/resource/definition_validator'


definition = MultiJson.load(File.read(ARGV[0]))
api = MultiJson.load(File.read(ARGV[1]))

errors = Aws::Resource::DefinitionValidator.new(definition, api).errors

if errors.empty?
  puts "OK"
  exit 0
else
  puts "ERRORS"
  puts " -  " + errors.join("\n -  ")
  exit 1
end
